export const DROP_FILE = "DROP_FILE";
export const DROP_FILE_START = "DROP_FILE_START";
export const DROP_FILE_FAIL = "DROP_FILE_FAIL";
export const DROP_FILE_SUCCESS = "DROP_FILE_SUCCESS";

export const FETCH_INFOS_START = "FETCH_INFOS_START";
export const FETCH_INFOS_FAIL = "FETCH_INFOS_FAIL";
export const FETCH_INFOS_SUCCESS = "FETCH_INFOS_SUCCESS";
